Repository albfree/WauwApp, pull requests merged in 2020-05, with the labels that each got.

#209 feat - Cantidad de dinero aportado a las protectoras
  components/screens/LoginScreen.js
  components/screens/Profile/PayRequest.js
Labels: HIGH

#210 feat - Se ocultan los chats asociados a una request finalizada
  components/screens/Chats.js
Labels: LOW

#213 Feat component/edit walker data
  components/__tests__/screens/createaccommodation.test.js
  components/__tests__/screens/home.test.js
  components/__tests__/screens/profile/profilelocationform.test.js
  components/__tests__/screens/services.test.js
  components/account/ChangeDescriptionForm.js
  components/account/ChangeNameForm.js
  components/account/InfoUser.js
  components/account/UserGuest.js
  components/navigations/Navigation.js
  components/screens/Chats.js
  components/screens/CreateAccommodation.js
  components/screens/CreateRequestAccommodation.js
  components/screens/CreateRequestWalk.js
  components/screens/DashboardScreen.js
  components/screens/EditDeleteAccommodation.js
  components/screens/FormFilterByAvailability.js
  components/screens/FormFilterByDate.js
  components/screens/FormRequestAccommodation.js
  components/screens/GRPD/UserData.js
  components/screens/Home.js
  components/screens/ListMyNotifications.js
  components/screens/LoadingScreen.js
  components/screens/News.js
  components/screens/Notifications.js
  components/screens/Profile/AddReviewService.js
  components/screens/Profile/LastConexion.js
  components/screens/Profile/Profile.js
  components/screens/Profile/ProfileAddDogForm.js
  components/screens/Profile/ProfileDeleteData.js
  components/screens/Profile/ProfileDisplayFinishRequest.js
  components/screens/Profile/ProfileLocationForm.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/Profile/ProfileMyDogs.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ProfileMyWalks.js
  components/screens/Profile/ProfileRequestsToMyAccommodationList.js
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
  components/screens/Services.js
Labels: BUG

#215 Feat component/edit walker data
  components/navigations/ProfileDrawer.js
  components/screens/CreateRequestAccommodation.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/Profile/ProfileMyDogs.js
Labels: HIGH

#217 Feat - mejora de localización
  components/screens/Profile/ProfileLocationForm.js
Labels: LOW

#218 fix - Arreglado redondeo del precio
  components/screens/Profile/PayRequest.js
Labels: BUG

#219 fix - Arreglo precio en el pago al usuario
  components/screens/Profile/AddReviewService.js
Labels: BUG

#220 fix - Arreglos en el pago y suma de puntos
  components/account/InfoUser.js
  components/screens/GRPD/UserData.js
  components/screens/Profile/PayRequest.js
Labels: BUG, HIGH

#221 Update EditDeleteAccommodation.js
  components/screens/EditDeleteAccommodation.js
Labels: ACCEPTED, BUG, LOW

#223 Feat - mejora de borrado
  components/screens/Profile/ProfileDeleteData.js
Labels: LOW

#225 fix - show Datepicker
  components/screens/CreateAccommodation.js
  components/screens/EditDeleteAccommodation.js
  components/screens/FormFilterByDate.js
  components/screens/FormRequestAccommodation.js
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/SearchAccommodations.js
Labels: HIGH

#227 Fix - mejora localización
  components/screens/Profile/ProfileLocationForm.js
Labels: HIGH

#228 App Style - revision
  components/screens/GRPD/UserData.js
  components/screens/Profile/ProfileDisplayFinishRequest.js
  components/screens/Profile/ProfileRequestsToMyAccommodationList.js
  components/styles/accommodationStyle.js
Labels: HIGH

#229 Feat component/edit walker data
  components/screens/LoginScreen.js
  components/screens/Profile/ProfileAddDogForm.js
  components/screens/Profile/ProfileMyDogs.js
  components/screens/Profile/ProfileWalkerForm.js
Labels: HIGH

#230 fix - arreglado borrado de requests.
  components/screens/Profile/ProfileDeleteData.js
Labels: HIGH

#231 Fix - Espacio disponibilidades
  components/screens/Profile/ProfileWalkerForm.js
  components/styles/walkerFormStyle.js
Labels: ACCEPTED, HIGH

#232 Fix - arreglo de borrado de solicitudes canceladas
  components/screens/Profile/ProfileDeleteData.js
Labels: HIGH
