Repository albfree/WauwApp, pull requests merged in 2020-04, with the labels that each got.

#96 fix - Nueva base de datos
  components/population/config.js
Labels: ACCEPTED, HIGH

#99 Feat component/edit walker data
  components/account/InfoUser.js
  components/account/UpdateAccount.js
  components/account/UserGuest.js
  components/screens/ListMyNotifications.js
  components/screens/Profile/Profile.js
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
Labels: LOW

#104 feature - Close Service #100
  components/navigations/Navigation.js
  components/navigations/ProfileDrawer.js
  components/navigations/ProfileStack.js
  components/screens/ListMyNotifications.js
  components/screens/Notifications.js
  components/screens/Profile/ProfileMyWalks.js
  components/screens/Profile/ShowRequest.js
  components/screens/Profile/ShowWalk.js
  components/styles/global.js
Labels: ACCEPTED, HIGH

#105 Fix component/request is finished
  components/screens/CreateRequestAccommodation.js
  components/screens/CreateRequestWalk.js
Labels: ACCEPTED, HIGH

#106 refactor - App styles
  assets/images/CreateAccommodation.jpg
  assets/images/CreateAccommodation2.jpg
  assets/images/SearchAccommodation.jpg
  assets/images/SearchWalk.jpg
  assets/images/create-accommodation.png
  assets/images/create-walk.png
  assets/images/search-accommodations.png
  assets/images/search-walks.png
  components/navigations/ChatsStack.js
  components/navigations/HomeStack.js
  components/navigations/NotificationsStack.js
  components/navigations/ProfileStack.js
  components/navigations/RequestStack.js
  components/navigations/ServicesStacks.js
  components/screens/LoginScreen.js
  components/screens/Services.js
  components/styles/global.js
  components/styles/loginStyle.js
  components/styles/servicesStyle.js
  dependencies.txt
  package-lock.json
  package.json
Labels: ACCEPTED, HIGH

#107 Feat component/terminos y condiciones
  App.js
  components/navigations/LoginStack.js
  components/screens/LoginScreen.js
  components/screens/Profile/ProfileAddDogForm.js
  components/screens/TermsAndConditions.js
  components/styles/loginStyle.js
Labels: ACCEPTED, HIGH

#115 feat - Navegación del perfil público
  components/account/PublicProfile.js
  components/navigations/RequestStack.js
  components/navigations/ServicesStacks.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
Labels: LOW

#116 Feat component/edit walker data
  components/navigations/ProfileStack.js
  components/screens/CreateRequestWalk.js
  components/screens/FormRequestAccommodation.js
  components/screens/LoginScreen.js
  components/screens/Profile/AddReviewService.js
  components/screens/Profile/ProfileAddDogForm.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/Profile/ShowRequest.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
  dependencies.txt
  package-lock.json
  package.json
Labels: HIGH

#118 feat - perfil público implementado
  components/account/PublicProfile.js
  components/styles/global.js
Labels: HIGH

#110 refactor - App Style
  assets/images/blank.jpg
  assets/images/happydoggo.jpg
  assets/images/shiba.jpg
  assets/images/usphoto.jpg
  components/navigations/LoginStack.js
  components/navigations/ProfileDrawer.js
  components/navigations/ServicesStacks.js
  components/screens/AnimalShelters.js
  components/screens/BlankView.js
  components/screens/Chats.js
  components/screens/CreateRequestWalk.js
  components/screens/FormFilterByAvailability.js
  components/screens/FormFilterByDate.js
  components/screens/Home.js
  components/screens/ListMyNotifications.js
  components/screens/LoginScreen.js
  components/screens/Profile/AboutUs.js
  components/screens/Profile/Profile.js
  components/screens/Profile/ProfileAddDogForm.js
  components/screens/Profile/ProfileLocationForm.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ProfileMyWalks.js
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
  components/screens/Services.js
  components/screens/TermsAndConditions.js
  components/styles/aboutStyle.js
  components/styles/addDogStyle.js
  components/styles/animalStyle.js
  components/styles/filterDateStyle.js
  components/styles/formSearchWalksStyle.js
  components/styles/global.js
  components/styles/homeStyle.js
  components/styles/locationStyles.js
  components/styles/loginStyle.js
  components/styles/searchWalkStyle.js
  components/styles/walkerFormStyle.js
Labels: ACCEPTED, HIGH

#121 Feat component/edit walker data
  components/account/MyReviews.js
  components/account/PublicProfile.js
  components/screens/Profile/AddReviewService.js
  components/screens/SearchWalks.js
  package-lock.json
  package.json
Labels: HIGH

#123 Test component/travis2
  .travis.yml
  components/__tests__/__snapshots__/login.test.js
  components/__tests__/screens/chats.test.js
  components/__tests__/screens/listmynotifications.test.js
  components/__tests__/screens/notifications.test.js
  components/__tests__/screens/profile/profilemyaccommodations.test.js
  components/__tests__/screens/profile/profilemyrequests.test.js
  components/__tests__/screens/profile/profilewalkerform.test.js
  components/__tests__/screens/searchaccommodation.test.js
  components/__tests__/screens/searchwalks.test.js
  components/__tests__/screens/services.test.js
  components/population/config.js
  package.json
Labels: ACCEPTED, HIGH

#125 Feat component/feedback service
  assets/images/feedback.jpg
  components/navigations/ProfileDrawer.js
  components/screens/Profile/AboutUs.js
  components/screens/Profile/Feedback.js
  components/styles/aboutStyle.js
  components/styles/loginStyle.js
Labels: ACCEPTED, LOW

#124 refactor - App Style #95
  components/screens/SearchAccommodations.js
  components/styles/homeStyle.js
  components/styles/searchAccommodationStyle.js
Labels: ACCEPTED, HIGH

#122 fix-dateRequestAccommodation
  components/screens/FormRequestAccommodation.js
Labels: HIGH

#131 feat - App Style #95
  components/navigations/ProfileDrawer.js
  components/screens/Profile/LastConexion.js
  components/screens/Profile/Profile.js
Labels: ACCEPTED, HIGH

#128 Fix component/bugs
  components/screens/CreateAccommodation.js
  components/screens/Profile/ProfileWalkerForm.js
Labels: ACCEPTED, HIGH

#129 Fix/precio-paseador
  components/screens/Profile/ProfileMyWalks.js
Labels: ACCEPTED, HIGH

#132 Feat component/edit walker data
  components/chat/Chat.js
  components/models/sits/ListAccommodations.js
  components/screens/Chats.js
  components/screens/CreateRequestWalk.js
  components/screens/FormFilterByAvailability.js
  components/screens/ListMyNotifications.js
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/Profile/ShowRequest.js
  components/screens/SearchWalks.js
Labels: HIGH

#134 Fix component/bugs
  components/account/ChangeDescriptionForm.js
  components/account/InfoUser.js
  components/account/LastLogged.js
  components/screens/Profile/Profile.js
  components/utils/DateParser.js
  dependencies.txt
  package-lock.json
  package.json
Labels: ACCEPTED, LOW

#137 Feat component/listar request de cada accommodation
  components/navigations/ProfileStack.js
  components/screens/CreateRequestAccommodation.js
  components/screens/EditDeleteAccommodation.js
  components/screens/Profile/ProfileDisplayFinishRequest.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/Profile/ProfileRequestsToMyAccommodationList.js
Labels: ACCEPTED, HIGH

#138 feat - show price My Availabilities / fix - delete availability bug
  components/screens/CreateRequestWalk.js
  components/screens/FormFilterByAvailability.js
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/SearchWalks.js
  package.json
Labels: HIGH

#140 fix/formato-fechas-request-accommodation
  components/screens/FormRequestAccommodation.js
  components/screens/SearchAccommodations.js
  package-lock.json
  package.json
Labels: HIGH

#141 Fix/formato fechas crear alojamiento
  components/screens/CreateRequestAccommodation.js
Labels: ACCEPTED, HIGH

#133 refactor - App Style
  components/account/MyReviews.js
  components/account/PublicProfile.js
  components/navigations/LoginStack.js
  components/navigations/Navigation.js
  components/screens/BlankView2.js
  components/screens/CreateAccommodation.js
  components/screens/CreateRequestAccommodation.js
  components/screens/CreateRequestWalk.js
  components/screens/DashboardScreen.js
  components/screens/FormFilterByAvailability.js
  components/screens/FormRequestAccommodation.js
  components/screens/LoginScreen.js
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
  components/styles/global.js
  components/styles/loginStyle.js
  components/styles/publicProfileStyle.js
  components/styles/searchAccommodationStyle.js
  components/styles/searchWalkStyle.js
  package-lock.json
  package.json
Labels: HIGH

#142 Fix component/comprobacion localizacion
  components/screens/Profile/Profile.js
  components/screens/Services.js
Labels: ACCEPTED, BUG, HIGH

#143 refactor - App Style
  components/chat/Chat.js
  components/navigations/ServicesStacks.js
  components/screens/Chats.js
  components/screens/ListMyNotifications.js
  components/screens/Profile/Feedback.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ShowRequest.js
  components/screens/SearchAccommodations.js
  components/styles/aboutStyle.js
  components/styles/chatsStyle.js
  components/styles/notificationsStyle.js
  components/styles/requestsStyle.js
Labels: HIGH

#144 feat - price/rating filter accomodation // fix - setWalkSalary
  components/screens/CreateAccommodation.js
  components/screens/Profile/ProfileAddDogForm.js
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/SearchAccommodations.js
Labels: HIGH

#145 feat - Wauw Points
  components/screens/Profile/PayRequest.js
Labels: HIGH

#136 GRPD
  components/navigations/ProfileStack.js
  components/population/config.js
  components/screens/GRPD/UserData.js
  components/screens/LoginScreen.js
  components/screens/Profile/Profile.js
  package-lock.json
  package.json
Labels: HIGH

#147 feat - Ordenar por distancia y vista logins
  components/account/InfoUser.js
  components/screens/LoginScreen.js
  components/screens/Profile/LastConexion.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
  components/utils/DateParser.js
Labels: HIGH

#146 refactor - App Style
  components/account/ChangeDescriptionForm.js
  components/account/ChangeNameForm.js
  components/account/InfoUser.js
  components/account/LastLogged.js
  components/account/UserGuest.js
  components/navigations/ProfileDrawer.js
  components/navigations/ProfileStack.js
  components/navigations/ServicesStacks.js
  components/screens/CreateRequestWalk.js
  components/screens/GRPD/UserData.js
  components/screens/Home.js
  components/screens/Profile/Profile.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ProfileMyWalks.js
  components/screens/Profile/ShowRequest.js
  components/screens/Profile/ShowWalk.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
  components/styles/homeStyle.js
  components/styles/myWalksStyle.js
  components/styles/profileStyle.js
  components/styles/requestsStyle.js
  components/styles/searchWalkStyle.js
  components/styles/userDataStyle.js
Labels: ACCEPTED, HIGH

#149 Feat - GDPR Eliminación de datos de usuario
  components/account/MyReviews.js
  components/account/QueriesProfile.js
  components/navigations/ProfileDrawer.js
  components/screens/Profile/AddReviewService.js
  components/screens/Profile/ProfileDeleteData.js
  package-lock.json
  package.json
Labels: HIGH

#154 feat - Cobro de vuelta al usuario
  components/navigations/ProfileStack.js
  components/navigations/ServicesStacks.js
  components/screens/Pagar.js
  components/screens/Pago.js
  components/screens/Profile/AddReviewService.js
  components/screens/Profile/Profile.js
  components/screens/Profile/ShowWalk.js
Labels: HIGH

#151 Bug - Editar ubicación
  components/screens/Profile/ProfileLocationForm.js
Labels: BUG, LOW

#156 fix - Arreglo datos información recopilada
  components/screens/GRPD/UserData.js
Labels: BUG

#153 Fix component/price salary accommodation
  components/screens/CreateAccommodation.js
  components/screens/CreateRequestAccommodation.js
  components/screens/SearchAccommodations.js
Labels: ACCEPTED, BUG, HIGH

#160 Feat component/baneo
  App.js
  assets/images/blocked.png
  components/__tests__/screens/profile/profile.test.js
  components/account/ChangeDescriptionForm.js
  components/account/ChangeNameForm.js
  components/account/InfoUser.js
  components/account/LastLogged.js
  components/account/MyReviews.js
  components/account/QueriesProfile.js
  components/account/UserGuest.js
  components/account/bannedAssertion.js
  components/navigations/ProfileDrawer.js
  components/navigations/ProfileStack.js
  components/navigations/ServicesStacks.js
  components/screens/Administrator/UserList.js
  components/screens/BannedScreen.js
  components/screens/Chats.js
  components/screens/CreateAccommodation.js
  components/screens/CreateRequestAccommodation.js
  components/screens/CreateRequestWalk.js
  components/screens/GRPD/UserData.js
  components/screens/Home.js
  components/screens/ListMyNotifications.js
  components/screens/LoadingScreen.js
  components/screens/LoginScreen.js
  components/screens/Pagar.js
  components/screens/Pago.js
  components/screens/Profile/AddReviewService.js
  components/screens/Profile/AdminPanel.js
  components/screens/Profile/LastConexion.js
  components/screens/Profile/PayRequest.js
  components/screens/Profile/Profile.js
  components/screens/Profile/ProfileAddDogForm.js
  components/screens/Profile/ProfileDeleteData.js
  components/screens/Profile/ProfileDisplayFinishRequest.js
  components/screens/Profile/ProfileLocationForm.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ProfileMyWalks.js
  components/screens/Profile/ProfileRequestsToMyAccommodationList.js
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/Profile/ShowRequest.js
  components/screens/Profile/ShowWalk.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
  components/screens/Services.js
  components/screens/TermsAndConditions.js
  components/styles/homeStyle.js
  components/styles/myWalksStyle.js
  components/styles/profileStyle.js
  components/styles/requestsStyle.js
  components/styles/searchWalkStyle.js
  components/styles/userDataStyle.js
  components/utils/DateParser.js
  package-lock.json
  package.json
Labels: HIGH

#162 feat - Cambio de foto de perfil
  app.json
  components/account/InfoUser.js
  components/account/UserGuest.js
Labels: HIGH

#161 fix - wauwer-delete price and walkSalary
  components/screens/LoginScreen.js
Labels: BUG, HIGH

#157 Fix/dates accommodation
  components/screens/CreateAccommodation.js
  components/screens/FormRequestAccommodation.js
Labels: BUG, HIGH

#159 Feat - avisos de administrador
  App.js
  assets/images/blocked.png
  components/navigations/BannedSwitchNavigator.js
  components/navigations/HomeStack.js
  components/navigations/ProfileDrawer.js
  components/navigations/ProfileStack.js
  components/screens/Administrator/AdminBroadcastForm.js
  components/screens/Administrator/UserList.js
  components/screens/BannedScreen.js
  components/screens/Home.js
  components/screens/LoadingScreen.js
  components/screens/LoginScreen.js
  components/screens/News.js
  components/screens/Profile/AdminPanel.js
  components/screens/Profile/Profile.js
  components/screens/Profile/ShowWalk.js
  components/screens/TermsAndConditions.js
Labels: HIGH

#163 Feat component/baneo
  components/account/bannedAssertion.js
  components/navigations/BannedSwitchNavigator.js
  components/navigations/ProfileStack.js
  components/screens/Chats.js
  components/screens/GRPD/UserData.js
  components/screens/Home.js
  components/screens/ListMyNotifications.js
  components/screens/Profile/Profile.js
  components/screens/Profile/ProfileAddDogForm.js
  components/screens/Profile/ProfileDisplayFinishRequest.js
  components/screens/Profile/ProfileLocationForm.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ProfileMyWalks.js
  components/screens/Profile/ProfileRequestsToMyAccommodationList.js
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/Profile/ShowRequest.js
  components/screens/Profile/ShowWalk.js
  components/screens/Services.js
Labels: ACCEPTED, HIGH

#152 refactor - App Style
  app.json
  assets/icon.png
  assets/icon2.png
  assets/images/MoneyDog.jpg
  assets/images/PoliceDog.jpg
  assets/images/SadDog.jpg
  components/account/InfoUser.js
  components/account/UpdateAccount.js
  components/models/walks/ListWauwers.js
  components/navigations/ProfileStack.js
  components/screens/Chats.js
  components/screens/CreateAccommodation.js
  components/screens/CreateRequestAccommodation.js
  components/screens/EditDeleteAccommodation.js
  components/screens/FormFilterByDate.js
  components/screens/GRPD/UserData.js
  components/screens/Home.js
  components/screens/ListMyNotifications.js
  components/screens/LoadingScreen.js
  components/screens/LoginScreen.js
  components/screens/Notifications.js
  components/screens/Pagar.js
  components/screens/Pago.js
  components/screens/Profile/AddReviewService.js
  components/screens/Profile/LastConexion.js
  components/screens/Profile/PayRequest.js
  components/screens/Profile/Profile.js
  components/screens/Profile/ProfileAddDogForm.js
  components/screens/Profile/ProfileDeleteData.js
  components/screens/Profile/ProfileDisplayFinishRequest.js
  components/screens/Profile/ProfileLocationForm.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ProfileMyWalks.js
  components/screens/Profile/ProfileRequestsToMyAccommodationList.js
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/Profile/ShowRequest.js
  components/screens/Profile/ShowWalk.js
  components/screens/SearchWalks.js
  components/screens/Services.js
  components/styles/accommodationStyle.js
  components/styles/filterDateStyle.js
  components/styles/global.js
  components/styles/homeStyle.js
  components/styles/locationStyles.js
  components/styles/payStyle.js
  components/styles/profileStyle.js
  components/styles/searchAccommodationStyle.js
  components/styles/searchWalkStyle.js
Labels: HIGH

#164 fix/baneo
  components/navigations/ProfileStack.js
  components/screens/Profile/ProfileDisplayFinishRequest.js
Labels: HIGH

#165 Fix - Update TermsAndConditions.js
  components/screens/TermsAndConditions.js
Labels: ACCEPTED, HIGH

#167 fix - show last logins
  components/screens/Profile/LastConexion.js
Labels: HIGH

#168 Update LoginScreen.js
  components/screens/LoginScreen.js
Labels: HIGH

#155 feat - Arreglo loading y home
  assets/images/paw.png
  components/screens/LoadingScreen.js
  components/styles/homeStyle.js
Labels: HIGH

#171 Feat component/edit walker data
  components/screens/Profile/ProfileWalkerForm.js
Labels: HIGH

#173 fixures
  components/screens/Administrator/UserList.js
  components/screens/CreateAccommodation.js
  components/screens/FormFilterByAvailability.js
  components/screens/FormFilterByDate.js
  components/styles/global.js
Labels: ACCEPTED, HIGH

#172 Fix - Descripción solucionado y precio
  components/screens/GRPD/UserData.js
Labels: BUG

#176 tanda de fallos arreglados
  components/navigations/LoginStack.js
  components/screens/Administrator/AdminBroadcastForm.js
  components/screens/BannedScreen.js
  components/screens/Profile/ProfileDeleteData.js
  components/styles/global.js
Labels: BUG, LOW

#177 fix - Cambiado email y espacios para mejor visualización
  components/screens/GRPD/UserData.js
Labels: BUG

#179 Feat component/edit walker data
  components/screens/Profile/ProfileWalkerForm.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
Labels: HIGH

#181 Fix component/unir error location pet
  components/screens/CreateAccommodation.js
  components/screens/FormFilterByDate.js
  components/screens/FormRequestAccommodation.js
  components/screens/Services.js
Labels: ACCEPTED, BUG, HIGH

#180 refactor - App Style
  babel.config.js
  components/Loading.js
  components/account/AccountOptions.js
  components/account/ChangeEmailForm.js
  components/account/Modal.js
  components/models/sits/ListAccommodations.js
  components/models/walks/ListWauwers.js
  components/navigations/HomeStack.js
  components/population/populateDB.js
  components/screens/CreateRequestAccommodation.js
  components/screens/CreateRequestWalk.js
  components/screens/EditDeleteAccommodation.js
  components/screens/News.js
  components/screens/Pago.js
  components/screens/Profile/PayRequest.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/styles/accommodationStyle.js
  components/styles/animalStyle.js
  components/styles/global.js
  components/styles/homeStyle.js
  components/styles/payStyle.js
  components/styles/searchWalkStyle.js
  components/utils/DateParser.js
  components/utils/Loading.js
Labels: ACCEPTED, HIGH

#182 Fix - Exportación de datos de usuario
  components/screens/GRPD/UserData.js
  components/screens/Profile/Profile.js
Labels: BUG, HIGH

#183 fix - ReqOwner removed
  components/screens/GRPD/UserData.js
Labels: BUG

#185 Bug - Eliminar usuario
  components/account/LastLogged.js
  components/screens/LoginScreen.js
Labels: BUG, HIGH

#187 Fix - Precios alojamientos
  components/screens/CreateAccommodation.js
Labels: BUG, HIGH

#188 Fix/cambios de on a once
  components/account/LastLogged.js
  components/account/bannedAssertion.js
  components/account/popUp.js
  components/screens/Chats.js
  components/screens/CreateAccommodation.js
  components/screens/CreateRequestAccommodation.js
  components/screens/CreateRequestWalk.js
  components/screens/FormRequestAccommodation.js
  components/screens/ListMyNotifications.js
  components/screens/News.js
  components/screens/Profile/AddReviewService.js
  components/screens/Profile/PayRequest.js
  components/screens/Profile/Profile.js
  components/screens/Profile/ProfileAddDogForm.js
  components/screens/Profile/ProfileDeleteData.js
  components/screens/Profile/ShowWalk.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
  components/screens/Services.js
Labels: ACCEPTED, HIGH

#189 fix - Menú deslizable
  components/screens/Profile/ProfileMyRequests.js
Labels: BUG

#190 Fix/cambios de on a once
  components/screens/Administrator/UserList.js
  components/screens/Profile/ProfileDisplayFinishRequest.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ProfileMyWalks.js
  components/screens/Profile/ProfileRequestsToMyAccommodationList.js
  components/screens/Profile/ShowRequest.js
  components/screens/SearchAccommodations.js
Labels: HIGH

#191 Feat component/edit walker data
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/SearchAccommodations.js
Labels: HIGH

#186 Test component/testing
  components/__tests__/screens/blankview.test.js
  components/__tests__/screens/blankview2.test.js
  components/__tests__/screens/formfilterbyavailability.test.js
  components/__tests__/screens/formfilterbydate.test.js
  components/__tests__/screens/login.test.js
  components/__tests__/screens/news.test.js
  components/__tests__/screens/termsandconditions.test.js
  components/__tests__/units/database.test.js
  components/__tests__/units/dateparser.test.js
Labels: LOW

#192 fix accommodation price
  components/screens/CreateAccommodation.js
  components/screens/Profile/ProfileWalkerForm.js
Labels: HIGH

#196 Feat - Nueva base de datos y tokens
  components/population/config.js
  components/screens/LoginScreen.js
Labels: HIGH

#199 fix - filters
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
Labels: HIGH

#198 fix - bug de anonimizado de requests de dos tipos para el mismo wauwer
  components/screens/Profile/ProfileDeleteData.js
Labels: BUG, HIGH

#200 fix/useEffect
  components/screens/Home.js
  components/screens/Profile/Profile.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ProfileMyWalks.js
Labels: HIGH

#201 Fix component/use effect
  components/screens/ListMyNotifications.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ProfileMyWalks.js
Labels: HIGH

#208 feature - Refresco de Páginas
  assets/icon.png
  assets/images/logo.png
  assets/splash.png
  assets/splash2.png
  components/navigations/ChatsStack.js
  components/navigations/HomeStack.js
  components/navigations/Navigation.js
  components/navigations/ProfileDrawer.js
  components/navigations/ProfileStack.js
  components/navigations/ServicesStacks.js
  components/screens/BlankView.js
  components/screens/BlankView2.js
  components/screens/Chats.js
  components/screens/FormFilterByAvailability.js
  components/screens/GRPD/UserData.js
  components/screens/ListMyNotifications.js
  components/screens/Profile/LastConexion.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/Profile/ProfileMyDogs.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ProfileMyWalks.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
  components/styles/global.js
Labels: ACCEPTED, HIGH

#207 feat - mejora de request
  components/screens/CreateRequestAccommodation.js
  components/screens/CreateRequestWalk.js
  components/screens/FormRequestAccommodation.js
  components/screens/SearchWalks.js
Labels: HIGH
