Repository albfree/WauwApp, pull requests merged in 2020-03, with the labels that each got.

#82 fix -Añadir perro
  components/screens/LoginScreen.js
  components/screens/Profile/ProfileAddDogForm.js
Labels: ACCEPTED, BUG, HIGH

#85 fix - fixing bugs
  App.js
  components/screens/AnimalShelters.js
  components/screens/ChangeAvailability.js
  components/screens/CreateRequestAccommodation.js
  components/screens/CreateRequestWalk.js
  components/screens/DashboardScreen.js
  components/screens/ListMyNotifications.js
  components/screens/LoadingScreen.js
  components/screens/Notifications.js
  components/screens/Profile/PayRequest.js
  components/screens/Profile/ProfileLocationForm.js
Labels: BUG

#83 feat - add pet shelter
  assets/images/protectora1.jpg
  assets/images/protectora2.jpg
  assets/images/protectora3.jpg
  components/screens/AnimalShelters.js
Labels: ACCEPTED, LOW

#84 feat - component/app style
  components/navigations/ProfileStack.js
  components/navigations/ServicesStacks.js
  components/screens/CreateAccommodation.js
  components/screens/CreateRequestAccommodation.js
  components/screens/EditDeleteAccommodation.js
  components/screens/FormRequestAccommodation.js
  components/screens/ListMyNotifications.js
  components/screens/Notifications.js
  components/screens/Profile/Profile.js
  components/screens/Profile/ProfileAddDogForm.js
  components/screens/Profile/ProfileLocationForm.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/Profile/ProfileMyRequests.js
  components/screens/Profile/ProfileSitterForm.js
  components/screens/Profile/ShowRequest.js
  components/screens/SearchAccommodations.js
  components/screens/SearchWalks.js
  components/styles/global.js
  package.json
Labels: ACCEPTED, HIGH

#86 Feat component/app style
  components/screens/CreateRequestWalk.js
  components/screens/SearchWalks.js
  components/styles/global.js
Labels: ACCEPTED, HIGH

#88 fix - Añadido campo petNumber al usuario
  components/screens/LoginScreen.js
  components/screens/Profile/ProfileAddDogForm.js
Labels: ACCEPTED, BUG, HIGH

#89 Fix - fixing bugs
  components/screens/Chats.js
  components/screens/CreateAccommodation.js
  components/screens/CreateRequestWalk.js
  components/screens/FormRequestAccommodation.js
  components/screens/ListMyNotifications.js
  components/screens/Profile/ProfileAddDogForm.js
  components/screens/Profile/ProfileMyAccommodations.js
  components/screens/Profile/ProfileMyRequests.js
Labels: BUG

#90 Update ShowRequest.js
  components/screens/Profile/ShowRequest.js
Labels: BUG
